#!/bin/bash
#
# Use the current directory as the working directory
#$ -cwd
# Merge output and error messages into single file
#$ -j y
# Name of the output file
#$ -o cs205hw.o$JOB_ID
# Shell environment
#$ -S /bin/bash
# Resonance queue system to use
# If more than 5min job, use -q gpu.q
#$ -q gpu-short.q
# The number of processes to launch [1-32]
# (Change the number)
#$ -pe orte 2

# Import environment and profile
. /etc/profile
module load courses/cs205/2012

# Launch the job with the above number of processes
# (Only change the python file)
#mpirun -n $NSLOTS python P1A.py
mpirun -n $NSLOTS --mca btl_tcp_if_include eth0 python ms_parallel.py
